config/routes.rb
Mysimpleplants::Application.routes.draw do

  devise_for :growers
  get 'registrations/thanks', controller: 'registrations', action: 'thanks'
  resources :registrations

  resources :orders

  resources :option_types

  resources :steps

  resources :line_item_options

  resources :line_items

  get '/carts/update_totals', to: 'carts#update_totals'
  get '/carts/update_quantity', to: 'carts#update_quantity'
  get '/carts/update_hated_plant', to: 'carts#update_hated_plant'
  get '/mycart' => 'carts#show'
  get '/growers/home', to: 'growers#show'
  get '/growers/edit_info', to: 'growers#edit_info'
  get '/growers/orders/:order_id', to: 'growers#show_order', as: 'growers_show_order'
  post '/growers/order_status_picked', to: 'growers#order_status_picked' 
  post '/growers/order_status_complete', to: 'growers#order_status_complete'
  post '/growers/master_picking_sheet', to: 'growers#master_picking_sheet'
  post '/growers/picking_sheets', to: 'growers#picking_sheets'
  get '/growers/shipping_label/:order_id', to: 'growers#shipping_label', as: 'growers_shipping_label'
  post '/growers/table', to: 'growers#table'
  post '/growers/totals', to: 'growers#totals'
  resources :growers
  resources :carts
  resources :pages
  resources :options

  resources :option_sets

  resources :grower_zip_codes

  get '/zip_codes/check_availability', to: 'zip_codes#check_availability'
  resources :zip_codes

  resources :zones

  resources :products
  get '/buy-plants', to: 'products#show', as: 'buy_plants', defaults: { id: 1 }

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :contacts

  root 'pages#show', defaults: { id: 8 }

  get 'register', to: 'registrations#new', as: 'register'
  get 'about-us', to: 'pages#show', as: 'about_us', defaults: { id: 2 }
  get 'how-it-works', to: 'pages#show', as: 'hiw', defaults: { id: 1 }
  get 'our-growers', to: 'pages#show', as: 'our_growers', defaults: { id: 4 }
  get 'plant-care', to: 'pages#show', as: 'plant_care', defaults: { id: 5 }
  get 'frequently-asked-questions', to: 'pages#show', as: 'faq', defaults: { id: 3 }
  get 'contact-us', to: 'contacts#new', as: 'contact_us'
  get 'terms-and-policies', to: 'pages#show', as: 'terms', defaults: { id: 7 }
  get 'sitemap', to: 'pages#show', as: 'sitemap', defaults: { id: 6 }

end

app/models/option_set.rb
# == Schema Information
#
# Table name: option_sets
#
#  id             :integer          not null, primary key
#  name           :string(255)
#  product_id     :integer
#  order_num      :integer
#  created_at     :datetime
#  updated_at     :datetime
#  step_id        :integer
#  default_value  :string(255)
#  option_type_id :integer
#

class OptionSet < ActiveRecord::Base

  has_many :options, order: 'order_num asc'
  belongs_to :product
  belongs_to :step
  belongs_to :option_type

end

app/controllers/option_sets_controller.rb
class OptionSetsController < InheritedResources::Base
end

app/helpers/option_sets_helper.rb
module OptionSetsHelper
end

app/views/option_sets/_form.html.erb
<%= form_for(@option_set) do |f| %>
  <% if @option_set.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@option_set.errors.count, "error") %> prohibited this option_set from being saved:</h2>

      <ul>
      <% @option_set.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :product_id %><br>
    <%= f.number_field :product_id %>
  </div>
  <div class="field">
    <%= f.label :order_num %><br>
    <%= f.number_field :order_num %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/option_sets/_product_option_step.html.erb
<div class="row step" id="step_<%= option_set_counter + 2 %>">
  <div class="col-md-7">
    <h2><span class="steps">Step <%= option_set_counter + 2 %>:</span> <%= option_set.title %></h2>
    <p><%= option_set.description %></p>
  </div>
  <div class="col-md-5" style="margin-top:32px;">
    <% if option_set.id == 1 
         choices = ['First Choice', 'Second Choice', 'Third Choice']
        (0..2).each do |i| %>
        <label for="options[<%= option_set_counter %>][<%= i %>]" class="sr-only"><%= choices[i] %></label>
        <select name="options[<%= option_set_counter %>][<%= i %>]" class="input-lg form-control color-select" style="margin-left:40px; width:80%;">
          <option value="" disabled selected><%= choices[i] %></option>
          <%= render partial: 'options/option_set_option', collection: option_set.options, as: :option %>
        </select>
    <%  end 
    else %>
    <label for="options[<%= option_set_counter %>]" class="sr-only"><%= option_set.name %></label>
    <select name="options[<%= option_set_counter %>]" class="input-lg form-control" style="margin-left:40px; width:80%;">
      <option value="" disabled selected>Select One...</option>
      <%= render partial: 'options/option_set_option', collection: option_set.options, as: :option %>
    </select>
    <% end %>
  </div>
</div>

app/views/option_sets/_step_option_set.html.erb
<% if option_set.option_type_id == 2 %>
  <%= render partial: option_set.option_type.template %>
<% else %>
  <select title="<%= option_set.name %>" name="options[]" class="input-lg form-control" style="margin-left:30px; width:80%;">
    <option value="" selected><%= option_set.default_value %></option>
    <%= render partial: 'options/option_set_option', collection: option_set.options, as: :option %>
  </select>
<% end %>

app/views/option_sets/edit.html.erb
<h1>Editing option_set</h1>

<%= render 'form' %>

<%= link_to 'Show', @option_set %> |
<%= link_to 'Back', option_sets_path %>

app/views/option_sets/index.html.erb
<h1>Listing option_sets</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Product</th>
      <th>Order num</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @option_sets.each do |option_set| %>
      <tr>
        <td><%= option_set.name %></td>
        <td><%= option_set.product_id %></td>
        <td><%= option_set.order_num %></td>
        <td><%= link_to 'Show', option_set %></td>
        <td><%= link_to 'Edit', edit_option_set_path(option_set) %></td>
        <td><%= link_to 'Destroy', option_set, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Option set', new_option_set_path %>

app/views/option_sets/new.html.erb
<h1>New option_set</h1>

<%= render 'form' %>

<%= link_to 'Back', option_sets_path %>

app/views/option_sets/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @option_set.name %>
</p>

<p>
  <strong>Product:</strong>
  <%= @option_set.product_id %>
</p>

<p>
  <strong>Order num:</strong>
  <%= @option_set.order_num %>
</p>

<%= link_to 'Edit', edit_option_set_path(@option_set) %> |
<%= link_to 'Back', option_sets_path %>