config/routes.rb
Mysimpleplants::Application.routes.draw do

  devise_for :growers
  get 'registrations/thanks', controller: 'registrations', action: 'thanks'
  resources :registrations

  resources :orders

  resources :option_types

  resources :steps

  resources :line_item_options

  resources :line_items

  get '/carts/update_totals', to: 'carts#update_totals'
  get '/carts/update_quantity', to: 'carts#update_quantity'
  get '/carts/update_hated_plant', to: 'carts#update_hated_plant'
  get '/mycart' => 'carts#show'
  get '/growers/home', to: 'growers#show'
  get '/growers/edit_info', to: 'growers#edit_info'
  get '/growers/orders/:order_id', to: 'growers#show_order', as: 'growers_show_order'
  post '/growers/order_status_picked', to: 'growers#order_status_picked' 
  post '/growers/order_status_complete', to: 'growers#order_status_complete'
  post '/growers/master_picking_sheet', to: 'growers#master_picking_sheet'
  post '/growers/picking_sheets', to: 'growers#picking_sheets'
  get '/growers/shipping_label/:order_id', to: 'growers#shipping_label', as: 'growers_shipping_label'
  post '/growers/table', to: 'growers#table'
  post '/growers/totals', to: 'growers#totals'
  resources :growers
  resources :carts
  resources :pages
  resources :options

  resources :option_sets

  resources :grower_zip_codes

  get '/zip_codes/check_availability', to: 'zip_codes#check_availability'
  resources :zip_codes

  resources :zones

  resources :products
  get '/buy-plants', to: 'products#show', as: 'buy_plants', defaults: { id: 1 }

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :contacts

  root 'pages#show', defaults: { id: 8 }

  get 'register', to: 'registrations#new', as: 'register'
  get 'about-us', to: 'pages#show', as: 'about_us', defaults: { id: 2 }
  get 'how-it-works', to: 'pages#show', as: 'hiw', defaults: { id: 1 }
  get 'our-growers', to: 'pages#show', as: 'our_growers', defaults: { id: 4 }
  get 'plant-care', to: 'pages#show', as: 'plant_care', defaults: { id: 5 }
  get 'frequently-asked-questions', to: 'pages#show', as: 'faq', defaults: { id: 3 }
  get 'contact-us', to: 'contacts#new', as: 'contact_us'
  get 'terms-and-policies', to: 'pages#show', as: 'terms', defaults: { id: 7 }
  get 'sitemap', to: 'pages#show', as: 'sitemap', defaults: { id: 6 }

end

app/models/grower_zip_code.rb
# == Schema Information
#
# Table name: grower_zip_codes
#
#  id          :integer          not null, primary key
#  zip_code_id :integer
#  grower_id   :integer
#  created_at  :datetime
#  updated_at  :datetime
#

class GrowerZipCode < ActiveRecord::Base

  has_many :growers
  has_many :zip_codes

end

app/controllers/grower_zip_codes_controller.rb
class GrowerZipCodesController < InheritedResources::Base
end

app/helpers/grower_zip_codes_helper.rb
module GrowerZipCodesHelper
end

app/views/grower_zip_codes/_form.html.erb
<%= form_for(@grower_zip_code) do |f| %>
  <% if @grower_zip_code.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@grower_zip_code.errors.count, "error") %> prohibited this grower_zip_code from being saved:</h2>

      <ul>
      <% @grower_zip_code.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :zip_code_id %><br>
    <%= f.number_field :zip_code_id %>
  </div>
  <div class="field">
    <%= f.label :grower_id %><br>
    <%= f.number_field :grower_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/grower_zip_codes/edit.html.erb
<h1>Editing grower_zip_code</h1>

<%= render 'form' %>

<%= link_to 'Show', @grower_zip_code %> |
<%= link_to 'Back', grower_zip_codes_path %>

app/views/grower_zip_codes/index.html.erb
<h1>Listing grower_zip_codes</h1>

<table>
  <thead>
    <tr>
      <th>Zip code</th>
      <th>Grower</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @grower_zip_codes.each do |grower_zip_code| %>
      <tr>
        <td><%= grower_zip_code.zip_code_id %></td>
        <td><%= grower_zip_code.grower_id %></td>
        <td><%= link_to 'Show', grower_zip_code %></td>
        <td><%= link_to 'Edit', edit_grower_zip_code_path(grower_zip_code) %></td>
        <td><%= link_to 'Destroy', grower_zip_code, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Grower zip code', new_grower_zip_code_path %>

app/views/grower_zip_codes/new.html.erb
<h1>New grower_zip_code</h1>

<%= render 'form' %>

<%= link_to 'Back', grower_zip_codes_path %>

app/views/grower_zip_codes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Zip code:</strong>
  <%= @grower_zip_code.zip_code_id %>
</p>

<p>
  <strong>Grower:</strong>
  <%= @grower_zip_code.grower_id %>
</p>

<%= link_to 'Edit', edit_grower_zip_code_path(@grower_zip_code) %> |
<%= link_to 'Back', grower_zip_codes_path %>