config/routes.rb
Mysimpleplants::Application.routes.draw do

  devise_for :growers
  get 'registrations/thanks', controller: 'registrations', action: 'thanks'
  resources :registrations

  resources :orders

  resources :option_types

  resources :steps

  resources :line_item_options

  resources :line_items

  get '/carts/update_totals', to: 'carts#update_totals'
  get '/carts/update_quantity', to: 'carts#update_quantity'
  get '/carts/update_hated_plant', to: 'carts#update_hated_plant'
  get '/mycart' => 'carts#show'
  get '/growers/home', to: 'growers#show'
  get '/growers/edit_info', to: 'growers#edit_info'
  get '/growers/orders/:order_id', to: 'growers#show_order', as: 'growers_show_order'
  post '/growers/order_status_picked', to: 'growers#order_status_picked' 
  post '/growers/order_status_complete', to: 'growers#order_status_complete'
  post '/growers/master_picking_sheet', to: 'growers#master_picking_sheet'
  post '/growers/picking_sheets', to: 'growers#picking_sheets'
  get '/growers/shipping_label/:order_id', to: 'growers#shipping_label', as: 'growers_shipping_label'
  post '/growers/table', to: 'growers#table'
  post '/growers/totals', to: 'growers#totals'
  resources :growers
  resources :carts
  resources :pages
  resources :options

  resources :option_sets

  resources :grower_zip_codes

  get '/zip_codes/check_availability', to: 'zip_codes#check_availability'
  resources :zip_codes

  resources :zones

  resources :products
  get '/buy-plants', to: 'products#show', as: 'buy_plants', defaults: { id: 1 }

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :contacts

  root 'pages#show', defaults: { id: 8 }

  get 'register', to: 'registrations#new', as: 'register'
  get 'about-us', to: 'pages#show', as: 'about_us', defaults: { id: 2 }
  get 'how-it-works', to: 'pages#show', as: 'hiw', defaults: { id: 1 }
  get 'our-growers', to: 'pages#show', as: 'our_growers', defaults: { id: 4 }
  get 'plant-care', to: 'pages#show', as: 'plant_care', defaults: { id: 5 }
  get 'frequently-asked-questions', to: 'pages#show', as: 'faq', defaults: { id: 3 }
  get 'contact-us', to: 'contacts#new', as: 'contact_us'
  get 'terms-and-policies', to: 'pages#show', as: 'terms', defaults: { id: 7 }
  get 'sitemap', to: 'pages#show', as: 'sitemap', defaults: { id: 6 }

end

app/controllers/option_types_controller.rb
class OptionTypesController < InheritedResources::Base
end

app/helpers/option_types_helper.rb
module OptionTypesHelper
end

app/views/option_types/_form.html.erb
<%= form_for(@option_type) do |f| %>
  <% if @option_type.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@option_type.errors.count, "error") %> prohibited this option_type from being saved:</h2>

      <ul>
      <% @option_type.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :template %><br>
    <%= f.text_field :template %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/option_types/edit.html.erb
<h1>Editing option_type</h1>

<%= render 'form' %>

<%= link_to 'Show', @option_type %> |
<%= link_to 'Back', option_types_path %>

app/views/option_types/index.html.erb
<h1>Listing option_types</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Template</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @option_types.each do |option_type| %>
      <tr>
        <td><%= option_type.name %></td>
        <td><%= option_type.template %></td>
        <td><%= link_to 'Show', option_type %></td>
        <td><%= link_to 'Edit', edit_option_type_path(option_type) %></td>
        <td><%= link_to 'Destroy', option_type, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Option type', new_option_type_path %>

app/views/option_types/new.html.erb
<h1>New option_type</h1>

<%= render 'form' %>

<%= link_to 'Back', option_types_path %>

app/views/option_types/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @option_type.name %>
</p>

<p>
  <strong>Template:</strong>
  <%= @option_type.template %>
</p>

<%= link_to 'Edit', edit_option_type_path(@option_type) %> |
<%= link_to 'Back', option_types_path %>