config/routes.rb
Mysimpleplants::Application.routes.draw do

  devise_for :growers
  get 'registrations/thanks', controller: 'registrations', action: 'thanks'
  resources :registrations

  resources :orders

  resources :option_types

  resources :steps

  resources :line_item_options

  resources :line_items

  get '/carts/update_totals', to: 'carts#update_totals'
  get '/carts/update_quantity', to: 'carts#update_quantity'
  get '/carts/update_hated_plant', to: 'carts#update_hated_plant'
  get '/mycart' => 'carts#show'
  get '/growers/home', to: 'growers#show'
  get '/growers/edit_info', to: 'growers#edit_info'
  get '/growers/orders/:order_id', to: 'growers#show_order', as: 'growers_show_order'
  post '/growers/order_status_picked', to: 'growers#order_status_picked' 
  post '/growers/order_status_complete', to: 'growers#order_status_complete'
  post '/growers/master_picking_sheet', to: 'growers#master_picking_sheet'
  post '/growers/picking_sheets', to: 'growers#picking_sheets'
  get '/growers/shipping_label/:order_id', to: 'growers#shipping_label', as: 'growers_shipping_label'
  post '/growers/table', to: 'growers#table'
  post '/growers/totals', to: 'growers#totals'
  resources :growers
  resources :carts
  resources :pages
  resources :options

  resources :option_sets

  resources :grower_zip_codes

  get '/zip_codes/check_availability', to: 'zip_codes#check_availability'
  resources :zip_codes

  resources :zones

  resources :products
  get '/buy-plants', to: 'products#show', as: 'buy_plants', defaults: { id: 1 }

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :contacts

  root 'pages#show', defaults: { id: 8 }

  get 'register', to: 'registrations#new', as: 'register'
  get 'about-us', to: 'pages#show', as: 'about_us', defaults: { id: 2 }
  get 'how-it-works', to: 'pages#show', as: 'hiw', defaults: { id: 1 }
  get 'our-growers', to: 'pages#show', as: 'our_growers', defaults: { id: 4 }
  get 'plant-care', to: 'pages#show', as: 'plant_care', defaults: { id: 5 }
  get 'frequently-asked-questions', to: 'pages#show', as: 'faq', defaults: { id: 3 }
  get 'contact-us', to: 'contacts#new', as: 'contact_us'
  get 'terms-and-policies', to: 'pages#show', as: 'terms', defaults: { id: 7 }
  get 'sitemap', to: 'pages#show', as: 'sitemap', defaults: { id: 6 }

end

app/models/line_item_option.rb
# == Schema Information
#
# Table name: line_item_options
#
#  id              :integer          not null, primary key
#  line_item_id    :integer
#  option_id       :integer
#  option_name     :string(255)
#  option_price    :decimal(, )
#  option_set_id   :integer
#  option_set_name :string(255)
#  created_at      :datetime
#  updated_at      :datetime
#

class LineItemOption < ActiveRecord::Base

  belongs_to :line_item

end

app/controllers/line_item_options_controller.rb
class LineItemOptionsController < InheritedResources::Base
end

app/helpers/line_item_options_helper.rb
module LineItemOptionsHelper
end

app/views/line_item_options/_form.html.erb
<%= form_for(@line_item_option) do |f| %>
  <% if @line_item_option.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@line_item_option.errors.count, "error") %> prohibited this line_item_option from being saved:</h2>

      <ul>
      <% @line_item_option.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :line_item_id %><br>
    <%= f.number_field :line_item_id %>
  </div>
  <div class="field">
    <%= f.label :option_id %><br>
    <%= f.number_field :option_id %>
  </div>
  <div class="field">
    <%= f.label :option_name %><br>
    <%= f.text_field :option_name %>
  </div>
  <div class="field">
    <%= f.label :option_price %><br>
    <%= f.text_field :option_price %>
  </div>
  <div class="field">
    <%= f.label :option_set_id %><br>
    <%= f.number_field :option_set_id %>
  </div>
  <div class="field">
    <%= f.label :option_set_name %><br>
    <%= f.text_field :option_set_name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/line_item_options/edit.html.erb
<h1>Editing line_item_option</h1>

<%= render 'form' %>

<%= link_to 'Show', @line_item_option %> |
<%= link_to 'Back', line_item_options_path %>

app/views/line_item_options/index.html.erb
<h1>Listing line_item_options</h1>

<table>
  <thead>
    <tr>
      <th>Line item</th>
      <th>Option</th>
      <th>Option name</th>
      <th>Option price</th>
      <th>Option set</th>
      <th>Option set name</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @line_item_options.each do |line_item_option| %>
      <tr>
        <td><%= line_item_option.line_item_id %></td>
        <td><%= line_item_option.option_id %></td>
        <td><%= line_item_option.option_name %></td>
        <td><%= line_item_option.option_price %></td>
        <td><%= line_item_option.option_set_id %></td>
        <td><%= line_item_option.option_set_name %></td>
        <td><%= link_to 'Show', line_item_option %></td>
        <td><%= link_to 'Edit', edit_line_item_option_path(line_item_option) %></td>
        <td><%= link_to 'Destroy', line_item_option, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Line item option', new_line_item_option_path %>

app/views/line_item_options/new.html.erb
<h1>New line_item_option</h1>

<%= render 'form' %>

<%= link_to 'Back', line_item_options_path %>

app/views/line_item_options/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Line item:</strong>
  <%= @line_item_option.line_item_id %>
</p>

<p>
  <strong>Option:</strong>
  <%= @line_item_option.option_id %>
</p>

<p>
  <strong>Option name:</strong>
  <%= @line_item_option.option_name %>
</p>

<p>
  <strong>Option price:</strong>
  <%= @line_item_option.option_price %>
</p>

<p>
  <strong>Option set:</strong>
  <%= @line_item_option.option_set_id %>
</p>

<p>
  <strong>Option set name:</strong>
  <%= @line_item_option.option_set_name %>
</p>

<%= link_to 'Edit', edit_line_item_option_path(@line_item_option) %> |
<%= link_to 'Back', line_item_options_path %>